name: Black Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black lint
        uses: psf/black@stable
        with:
          version: '~= 23.3.0'
